### ISSUE TITLE
Consider a config option or allowing specifying current-context in the kubeconfig template

### ISSUE THREAD

**Issue by SEJeff** [negz/kuberos#19]
When I set `current-context: foobar` in my kubeconfig template, the rendered kubeconfig still has it set null.

This is my kuberos kubeconfig configmap:

```
apiVersion: v1
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    current-context: minikube
    clusters:
    - name: minikube
      cluster:
        certificate-authority-data: [LOTS OF CERT DATA HERE]
        server: https://192.168.99.100:8443 # from minikube ip
kind: ConfigMap
metadata:

  name: kuberos-kubeconfig
  namespace: auth
```

The rendered kubeconfig zeros out the `current-context` line. I'd like for that line to be preserved if it is in the template.
