### ISSUE TITLE
kuberos ingress via traefik not working

### ISSUE THREAD

**Issue by amit-handa** [negz/kuberos#38]
Hi,

w.r.t. https://github.com/negz/kuberos/pull/27#issuecomment-390925198

I am using kuberos,dex via traefik ingress. all are on latest versions. I am unable to redirect.
the curl command specified in the comments above is working correctly though.
sorry, if I shouldnt comment here, I ll create an issue otherwise.
logs of the invocation are as follows:

```
time="2018-05-22T09:19:13Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,/;q=0.8"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-IN,en-GB;q=0.9,en-US;q=0.8,en;q=0.7"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"],*"X-Forwarded-Prefix":["/kuberos"]**},"ContentLength":0,"TransferEncoding":null,"Host":"k8s.gemsol.in:31689","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"192.168.219.64:42094","RequestURI":"/","TLS":null}"
...
...
time="2018-05-22T09:19:13Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"192.168.135.52:5556","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,/*;q=0.8"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-IN,en-GB;q=0.9,en-US;q=0.8,en;q=0.7"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"],"X-Forwarded-Prefix":["/"]},"ContentLength":0,"TransferEncoding":null,"Host":"k8s.gemsol.in:31689","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"192.168.219.64:42094","RequestURI":"/dex/auth?client_id=gem-kube\u0026prompt=consent\u0026redirect_uri=https%3A%2F%2Fk8s.gemsol.in%3A31689%2Fui\u0026response_type=code\u0026scope=openid+offline_access+groups+email\u0026state=9454ad698774a8d771efa17d8f36b85c314630154c01b6a4f46da708b654801e","TLS":null}"
```

**Comment by negz** [comment]
@amit-handa I'm afraid I don't have experience running Kuberos behind an ingress. Perhaps @Miouge1 has some advice?

**Comment by Miouge1** [comment]
I'm running Kuberos with Traefik as an Ingress without any problems. Can you dump your ingress config?

**Comment by amit-handa** [comment]
I only used prefixpathstrip annotation with traefik and provided '/kuberos'  as path, in the ingress object.

**Comment by Miouge1** [comment]
@amit-handa hard to help without the Ingress manifest. Here is mine:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
  name: kuberos
spec:
  rules:
  - host: kubernetes.example.com
    http:
      paths:
      - backend:
          serviceName: kuberos
          servicePort: 80
        path: /kuberos/
  tls:
  - hosts:
    - kubernetes.example.com
    secretName: mysecret
```

**Comment by amit-handa** [comment]
@Miouge1 apologies for the delay
I used following ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuberos
  namespace: auth
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: k8s.corp.in
    http:
      paths:
      - backend:
          serviceName: kuberos
          servicePort: 10003
        path: /kuberos
```
The error I get it that when I open http://k8s.corp.in:<ingress-port>/kuberos
I am redirected to dex service : 
https://dex.corp.in/dex/auth?client_id=gem-kube&prompt=consent&redirect_uri=http%3A%2F%2Fk8s.corp.in%3A32084%2Fui&response_type=code&scope=openid+offline_access+groups+email&state=88cf9678840717ce2e799ee182dca461fdc9ffc3fafab18eef8b4ae9d3ffb5ac

And I see following error:
```
Bad Request

Unregistered redirect_uri ("http://k8s.corp.in:32084/ui").
```
please note that _/kuberos is missing_ in the url. Let me know if you need any other info.
